import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import Header from "@/components/ui/Header";
import { Footer } from "@/components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const name = "Endy Gómez";
export const siteTitle = "Next.js Sample Website";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={inter.className}>
        <Header name={name} />

        <main className="grid grid-cols-12 w-full text-left h-full min-h-screen">
          {children}
        </main>

        <div className="grid grid-cols-12 w-full">
          <Footer />
        </div>
      </body>
    </html>
  );
}

// lg:2/6 xl:w-2/4 lg:mt-20 lg:ml-16 ml-16 mr-16
